# -*- coding: utf-8 -*-
"""AirportData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16mh7kWhltZ9oiXeDNukU97oFE_oXkjYq
"""

import pandas as pd

airports = pd.read_csv("airports.csv")
airports = airports.drop(['ICAO', 'Altitude', 'Timezone', 'DST', 'Timezone.1'], axis=1)
routes = pd.read_csv("routes.csv")
routes = routes.drop(['Source Airport ID', 'Destination Airport ID', 'Codeshare', 'Equipment'], axis=1)
routes